# Generated by Django 5.1.15 on 2026-05-21 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Numéro d'Identification Fiscale",
                        max_length=30,
                        verbose_name="NIF",
                    ),
                ),
                (
                    "stat",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Statistique — numéro d'identification entreprise",
                        max_length=30,
                        verbose_name="STAT",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Adresse e-mail",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Adresse"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["company_name"],
                "indexes": [
                    models.Index(fields=["company_name"], name="idx_client_name"),
                    models.Index(fields=["is_active"], name="idx_client_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Format : INV-YYYY-NNNN",
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'émission",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "amount_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "tva_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "amount_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENT", "Envoyée"),
                            ("PAID", "Payée"),
                            ("OVERDUE", "En retard"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="invoicing.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_invoice_status"),
                    models.Index(fields=["issue_date"], name="idx_invoice_date"),
                    models.Index(fields=["due_date"], name="idx_invoice_due"),
                ],
            },
        ),
    ]
