# Generated by Django 5.1.15 on 2026-05-21 14:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salaire brut mensuel en Ariary",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Salaire de base",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Date d'embauche")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "dependants_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de personnes à charge pour la réduction IRSA",
                        verbose_name="Personnes à charge",
                    ),
                ),
                (
                    "cnaps_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Numéro CNaPS",
                    ),
                ),
                (
                    "organism_sanitaire",
                    models.CharField(
                        choices=[
                            ("OSTIE", "OSTIE"),
                            ("AMIT", "AMIT"),
                            ("ESIA", "ESIA"),
                            ("FUNHECE", "FUNHECE"),
                        ],
                        default="OSTIE",
                        help_text="OSTIE, AMIT, ESIA ou FUNHECE selon la région",
                        max_length=10,
                        verbose_name="Organisme sanitaire",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="L'employé est-il toujours en activité ?",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="idx_employee_name"
                    ),
                    models.Index(fields=["is_active"], name="idx_employee_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="Mois du bulletin (1-12)", verbose_name="Mois"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Année du bulletin", verbose_name="Année"
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salaire brut"
                    ),
                ),
                (
                    "cnaps_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Cotisation CNaPS salarié",
                    ),
                ),
                (
                    "ostie_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Cotisation OSTIE/AMIT salarié",
                    ),
                ),
                (
                    "fmfp_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Cotisation FMFP salarié",
                    ),
                ),
                (
                    "irsa_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="IRSA",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salaire net"
                    ),
                ),
                (
                    "dependants_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de personnes à charge au moment du calcul",
                        verbose_name="Personnes à charge (snapshot)",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payé")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payslips/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.employee",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin de paie",
                "verbose_name_plural": "Bulletins de paie",
                "ordering": ["-year", "-month", "employee__last_name"],
                "indexes": [
                    models.Index(fields=["year", "month"], name="idx_payslip_period"),
                    models.Index(fields=["is_paid"], name="idx_payslip_paid"),
                ],
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
